apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-1
spec:
  replicas: 2
  selector:
    matchLabels:
       app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
      - name: otus-1
        image: volta854/otus:v1
        ports:
          - name: web
            containerPort: 80
